Default: &defaults
  user: yesoddev 
  password: yesoddev
  host: jellyfish85.com
  port: 3306
  database: yesoddev
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: firstYesod_test
  <<: *defaults

Staging:
  database: firstYesod_staging
  poolsize: 100
  <<: *defaults

Production:
  database: firstYesod_production
  poolsize: 100
  <<: *defaults
