Default: &defaults
  user: firstYesod
  password: firstYesod
  host: localhost
  port: 5432
  database: firstYesod
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: firstYesod_test
  <<: *defaults

Staging:
  database: firstYesod_staging
  poolsize: 100
  <<: *defaults

Production:
  database: firstYesod_production
  poolsize: 100
  <<: *defaults
